from classes.classe_pessoa import Pessoa

p1 = Pessoa('Luiz', 10)
p2 = Pessoa('Ana', 15)

p1.identificar()
p2.identificar()
print(p1.get_ano_nascimento())
print(p2.get_ano_nascimento())
print()

p1.comer('maçã')
p1.comer('laranja')
p1.parar_comer()
p1.comer('laranja')
p1.falar('moda')
p1.parar_comer()
p1.falar('informática')
p1.falar('terror')
p1.parar_falar()
p1.comer('feijão')
p1.parar_falar()
p1.parar_comer()
p1.parar_falar()
p1.comer('arroz')
p1.falar('amor')
p1.parar_falar()
p1.parar_comer()
p1.falar('amor')
p2.falar('esperança')
p2.parar_falar()
